name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode 13.2 for backward compatible Swift concurrency
      run: sudo xcode-select -switch /Applications/Xcode_13.2.app
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
